/**
 * GENERATED FILE — do not edit.
 *
 * Emitted from `@gs/errors` by `pnpm --filter @gs/web errors:emit`. `errors:check` runs in
 * CI and fails if this file has drifted from the catalog, so the published error reference
 * cannot describe an error the API does not return.
 */

export interface GeneratedErrorCode {
  code: string;
  type: string;
  status: number;
  retryable: boolean;
  message: string;
  agentAction?: string;
}

export const ERROR_CATALOG: readonly GeneratedErrorCode[] = [
  { code: "AUTHENTICATION_REQUIRED", type: "authentication_error", status: 401, retryable: false, message: "An API key is required. Send it as `Authorization: Bearer sk_live_...`.", agentAction: "supply_api_key" },
  { code: "API_KEY_INVALID", type: "authentication_error", status: 401, retryable: false, message: "The API key is not valid.", agentAction: "supply_valid_api_key" },
  { code: "API_KEY_REVOKED", type: "authentication_error", status: 401, retryable: false, message: "This API key has been revoked.", agentAction: "create_new_api_key" },
  { code: "API_KEY_EXPIRED", type: "authentication_error", status: 401, retryable: false, message: "This API key has expired.", agentAction: "create_new_api_key" },
  { code: "API_KEY_MALFORMED", type: "authentication_error", status: 401, retryable: false, message: "The API key is malformed. Expected a key beginning with `sk_test_` or `sk_live_`.", agentAction: "supply_valid_api_key" },
  { code: "INSUFFICIENT_SCOPE", type: "authorization_error", status: 403, retryable: false, message: "This API key does not have the scope required for this operation.", agentAction: "request_key_with_required_scope" },
  { code: "ENVIRONMENT_MISMATCH", type: "authorization_error", status: 403, retryable: false, message: "The resource belongs to a different environment than this API key.", agentAction: "use_matching_environment_key" },
  { code: "TENANT_FORBIDDEN", type: "authorization_error", status: 403, retryable: false, message: "The requested resource does not belong to this project.", agentAction: "use_a_resource_owned_by_this_project" },
  { code: "INVALID_REQUEST", type: "validation_error", status: 400, retryable: false, message: "The request body failed validation.", agentAction: "fix_request_body" },
  { code: "MISSING_REQUIRED_FIELD", type: "validation_error", status: 400, retryable: false, message: "A required field is missing.", agentAction: "supply_required_field" },
  { code: "UNSUPPORTED_CONTENT_TYPE", type: "validation_error", status: 415, retryable: false, message: "Send `Content-Type: application/json`.", agentAction: "use_json_content_type" },
  { code: "REQUEST_TOO_LARGE", type: "validation_error", status: 413, retryable: false, message: "The request body is too large. Upload media through the media endpoints instead of inline.", agentAction: "upload_media_via_media_endpoint" },
  { code: "UNSUPPORTED_API_VERSION", type: "validation_error", status: 400, retryable: false, message: "The requested API version is not supported.", agentAction: "use_supported_api_version" },
  { code: "PROFILE_NOT_FOUND", type: "not_found_error", status: 404, retryable: false, message: "No such profile.", agentAction: "list_profiles" },
  { code: "CONNECTION_NOT_FOUND", type: "not_found_error", status: 404, retryable: false, message: "No such connection.", agentAction: "list_connections" },
  { code: "DESTINATION_NOT_FOUND", type: "not_found_error", status: 404, retryable: false, message: "No such destination.", agentAction: "list_destinations" },
  { code: "MEDIA_NOT_FOUND", type: "not_found_error", status: 404, retryable: false, message: "No such media asset.", agentAction: "upload_media" },
  { code: "POST_NOT_FOUND", type: "not_found_error", status: 404, retryable: false, message: "No such post.", agentAction: "list_posts" },
  { code: "TARGET_NOT_FOUND", type: "not_found_error", status: 404, retryable: false, message: "No such publish target.", agentAction: "get_post" },
  { code: "WEBHOOK_NOT_FOUND", type: "not_found_error", status: 404, retryable: false, message: "No such webhook endpoint.", agentAction: "list_webhooks" },
  { code: "DELIVERY_NOT_FOUND", type: "not_found_error", status: 404, retryable: false, message: "No such webhook delivery.", agentAction: "list_webhook_deliveries" },
  { code: "RESOURCE_NOT_FOUND", type: "not_found_error", status: 404, retryable: false, message: "The requested resource does not exist." },
  { code: "IDEMPOTENCY_KEY_REQUIRED", type: "idempotency_error", status: 400, retryable: false, message: "An Idempotency-Key header is required for this operation.", agentAction: "retry_with_an_idempotency_key" },
  { code: "IDEMPOTENCY_KEY_REUSED", type: "idempotency_error", status: 409, retryable: false, message: "This Idempotency-Key was already used with a different request body.", agentAction: "use_a_new_idempotency_key" },
  { code: "IDEMPOTENCY_REQUEST_IN_PROGRESS", type: "idempotency_error", status: 409, retryable: true, message: "A request with this Idempotency-Key is still being processed. Retry shortly.", agentAction: "retry_after_delay" },
  { code: "DUPLICATE_CONTENT_BLOCKED", type: "conflict_error", status: 409, retryable: false, message: "Equivalent content was recently published to this destination. Set `allow_duplicate: true` to override.", agentAction: "set_allow_duplicate_or_change_content" },
  { code: "POST_NOT_CANCELLABLE", type: "conflict_error", status: 409, retryable: false, message: "This post can no longer be cancelled because publishing has begun or completed.", agentAction: "inspect_post_status" },
  { code: "POST_NOT_RETRYABLE", type: "conflict_error", status: 409, retryable: false, message: "This post has no targets in a retryable state.", agentAction: "inspect_post_targets" },
  { code: "TARGET_NOT_RETRYABLE", type: "conflict_error", status: 409, retryable: false, message: "This target is not in a retryable state.", agentAction: "inspect_target_status" },
  { code: "CONFLICTING_STATE", type: "conflict_error", status: 409, retryable: false, message: "The resource changed while this request was in flight.", agentAction: "reload_and_retry" },
  { code: "RESOURCE_ALREADY_EXISTS", type: "conflict_error", status: 409, retryable: false, message: "A resource with that identifier already exists.", agentAction: "fetch_the_existing_resource_or_choose_another_identifier" },
  { code: "CONNECTION_REAUTH_REQUIRED", type: "connection_error", status: 409, retryable: false, message: "The social connection must be re-authorized before it can publish.", agentAction: "create_connect_session_for_reauthorization" },
  { code: "CONNECTION_DISCONNECTED", type: "connection_error", status: 409, retryable: false, message: "The social connection is disconnected.", agentAction: "create_connect_session_for_reauthorization" },
  { code: "CONNECTION_REVOKED", type: "connection_error", status: 409, retryable: false, message: "Access was revoked at the provider.", agentAction: "create_connect_session_for_reauthorization" },
  { code: "CONNECTION_PERMISSION_MISSING", type: "connection_error", status: 409, retryable: false, message: "The connection is missing a permission required for this operation.", agentAction: "reauthorize_with_required_scopes" },
  { code: "CONNECTION_INCOMPLETE_SETUP", type: "connection_error", status: 409, retryable: false, message: "This connection requires a destination selection before it can publish.", agentAction: "select_destination_for_connection" },
  { code: "CONNECTION_RATE_LIMITED", type: "rate_limit_error", status: 429, retryable: true, message: "This social account is currently rate limited by the provider.", agentAction: "retry_after_delay" },
  { code: "PROVIDER_NOT_CONFIGURED", type: "connection_error", status: 503, retryable: true, message: "This platform is not yet available for connecting. Its application credentials are not configured.", agentAction: "check_platform_availability" },
  { code: "PROVIDER_TEMPORARILY_DISABLED", type: "connection_error", status: 503, retryable: true, message: "Publishing to this platform is temporarily switched off.", agentAction: "retry_later_or_publish_to_another_destination" },
  { code: "APPROVAL_ALREADY_DECIDED", type: "conflict_error", status: 409, retryable: false, message: "This approval request has already been decided.", agentAction: "read_the_current_decision" },
  { code: "AUTHORIZATION_SESSION_INVALID", type: "connection_error", status: 400, retryable: false, message: "This authorization link is invalid, already used, or expired.", agentAction: "start_authorization_again" },
  { code: "AUTHORIZATION_FAILED", type: "connection_error", status: 400, retryable: false, message: "The provider did not complete the authorization.", agentAction: "start_authorization_again" },
  { code: "AUTHORIZATION_CREDENTIAL_REJECTED", type: "connection_error", status: 400, retryable: false, message: "The provider rejected the supplied credential.", agentAction: "check_credential_and_try_again" },
  { code: "REDIRECT_URL_NOT_ALLOWED", type: "validation_error", status: 400, retryable: false, message: "That redirect URL is not permitted. It must be absolute HTTPS.", agentAction: "use_an_allowed_https_redirect_url" },
  { code: "CONNECT_SESSION_INVALID", type: "connection_error", status: 400, retryable: false, message: "This connect session is expired, already completed, or unknown.", agentAction: "create_connect_session" },
  { code: "CAPABILITY_NOT_SUPPORTED", type: "validation_error", status: 422, retryable: false, message: "The destination does not support this capability.", agentAction: "check_destination_capabilities" },
  { code: "POST_TYPE_NOT_SUPPORTED", type: "validation_error", status: 422, retryable: false, message: "The destination does not support this post type.", agentAction: "choose_supported_post_type" },
  { code: "TEXT_TOO_LONG", type: "validation_error", status: 422, retryable: false, message: "The text exceeds the destination limit.", agentAction: "shorten_text" },
  { code: "TEXT_REQUIRED", type: "validation_error", status: 422, retryable: false, message: "This destination requires text content.", agentAction: "supply_text" },
  { code: "MEDIA_REQUIRED", type: "validation_error", status: 422, retryable: false, message: "This destination requires at least one media item.", agentAction: "attach_media" },
  { code: "MEDIA_COUNT_EXCEEDED", type: "validation_error", status: 422, retryable: false, message: "Too many media items for this destination.", agentAction: "reduce_media_count" },
  { code: "MEDIA_TYPE_UNSUPPORTED", type: "media_error", status: 422, retryable: false, message: "The media type is not supported by this destination.", agentAction: "create_media_variant" },
  { code: "MEDIA_RATIO_UNSUPPORTED", type: "media_error", status: 422, retryable: false, message: "The media aspect ratio is not valid for this destination.", agentAction: "create_or_select_a_compliant_media_variant" },
  { code: "MEDIA_TOO_LARGE", type: "media_error", status: 422, retryable: false, message: "The media file exceeds the destination size limit.", agentAction: "create_media_variant" },
  { code: "MEDIA_DURATION_UNSUPPORTED", type: "media_error", status: 422, retryable: false, message: "The video duration is outside the range this destination accepts.", agentAction: "trim_video_duration" },
  { code: "MEDIA_RESOLUTION_UNSUPPORTED", type: "media_error", status: 422, retryable: false, message: "The media resolution is not valid for this destination.", agentAction: "create_media_variant" },
  { code: "MEDIA_NOT_READY", type: "media_error", status: 409, retryable: true, message: "The media asset is still being processed.", agentAction: "wait_for_media_ready_webhook" },
  { code: "MEDIA_MIXED_TYPES_UNSUPPORTED", type: "media_error", status: 422, retryable: false, message: "This destination cannot mix images and video in one post.", agentAction: "split_into_separate_posts" },
  { code: "LINK_NOT_SUPPORTED", type: "validation_error", status: 422, retryable: false, message: "This destination does not support link attachments.", agentAction: "remove_link" },
  { code: "PROVIDER_OPTION_INVALID", type: "validation_error", status: 422, retryable: false, message: "A provider-specific option is invalid.", agentAction: "fix_provider_option" },
  { code: "PROVIDER_OPTION_REQUIRED", type: "validation_error", status: 422, retryable: false, message: "A provider-specific option is required for this destination.", agentAction: "supply_required_provider_option" },
  { code: "PRIVACY_SELECTION_REQUIRED", type: "validation_error", status: 422, retryable: false, message: "This destination requires an explicit privacy level.", agentAction: "choose_allowed_privacy_level" },
  { code: "COMPLIANCE_DECLARATION_REQUIRED", type: "validation_error", status: 422, retryable: false, message: "This destination requires a compliance declaration before publishing.", agentAction: "supply_required_compliance_declaration" },
  { code: "SCHEDULE_IN_PAST", type: "validation_error", status: 422, retryable: false, message: "`publish_at` must be in the future.", agentAction: "choose_future_publish_at" },
  { code: "SCHEDULE_TOO_FAR_AHEAD", type: "validation_error", status: 422, retryable: false, message: "`publish_at` is beyond the maximum scheduling horizon.", agentAction: "choose_nearer_publish_at" },
  { code: "SCHEDULE_NOT_SUPPORTED", type: "validation_error", status: 422, retryable: false, message: "This destination does not support scheduled publishing.", agentAction: "publish_immediately" },
  { code: "VALIDATION_FAILED", type: "validation_error", status: 422, retryable: false, message: "One or more publish targets cannot accept this content as composed.", agentAction: "run_preflight_and_fix_reported_issues" },
  { code: "TARGETS_REQUIRED", type: "validation_error", status: 422, retryable: false, message: "At least one target is required.", agentAction: "add_target" },
  { code: "DUPLICATE_DESTINATION", type: "validation_error", status: 422, retryable: false, message: "The same destination appears more than once in `targets`.", agentAction: "deduplicate_targets" },
  { code: "RATE_LIMITED", type: "rate_limit_error", status: 429, retryable: true, message: "Too many requests. Slow down.", agentAction: "retry_after_delay" },
  { code: "QUOTA_EXCEEDED", type: "rate_limit_error", status: 429, retryable: true, message: "A provider quota for this account is exhausted.", agentAction: "retry_after_quota_reset" },
  { code: "PLAN_LIMIT_REACHED", type: "rate_limit_error", status: 402, retryable: false, message: "Your plan limit has been reached.", agentAction: "upgrade_plan_or_wait_for_period_reset" },
  { code: "PROVIDER_NOT_SUPPORTED", type: "validation_error", status: 400, retryable: false, message: "This provider is not supported.", agentAction: "check_supported_providers" },
  { code: "PROVIDER_UNAVAILABLE", type: "provider_error", status: 503, retryable: true, message: "The social provider is temporarily unavailable.", agentAction: "retry_after_delay" },
  { code: "PROVIDER_TIMEOUT", type: "provider_error", status: 504, retryable: true, message: "The social provider did not respond in time.", agentAction: "retry_after_delay" },
  { code: "PROVIDER_REJECTED_CONTENT", type: "provider_error", status: 422, retryable: false, message: "The provider rejected this content.", agentAction: "revise_content" },
  { code: "PROVIDER_CONFLICT", type: "provider_error", status: 409, retryable: false, message: "The provider reported a conflicting state.", agentAction: "inspect_target_status" },
  { code: "PROVIDER_ACCOUNT_NOT_ELIGIBLE", type: "provider_error", status: 422, retryable: false, message: "The connected account is not eligible for this operation.", agentAction: "check_destination_capabilities" },
  { code: "POSSIBLE_DUPLICATE", type: "provider_error", status: 409, retryable: false, message: "The provider indicates equivalent content may already exist.", agentAction: "inspect_destination_before_retrying" },
  { code: "RECONCILIATION_REQUIRED", type: "provider_error", status: 409, retryable: false, message: "The outcome of the previous publish attempt is unknown and is being reconciled. Do not retry blindly.", agentAction: "wait_for_reconciliation" },
  { code: "UNKNOWN_PROVIDER_ERROR", type: "provider_error", status: 502, retryable: false, message: "The provider returned an error we could not classify.", agentAction: "inspect_post_timeline" },
  { code: "MEDIA_UPLOAD_INCOMPLETE", type: "media_error", status: 409, retryable: false, message: "The upload was never completed. Call the upload completion endpoint.", agentAction: "complete_media_upload" },
  { code: "MEDIA_PROBE_FAILED", type: "media_error", status: 422, retryable: false, message: "The media file could not be read. It may be corrupt or an unsupported container.", agentAction: "upload_a_different_file" },
  { code: "MEDIA_PROCESSING_FAILED", type: "media_error", status: 422, retryable: false, message: "Media processing failed.", agentAction: "upload_a_different_file" },
  { code: "MEDIA_URL_NOT_ALLOWED", type: "media_error", status: 422, retryable: false, message: "The media URL is not allowed. It must be a public HTTPS URL that does not resolve to a private network.", agentAction: "use_public_https_url_or_upload_media" },
  { code: "MODEL_PROVIDER_NOT_CONFIGURED", type: "api_error", status: 503, retryable: false, message: "No model provider is configured. Content Intelligence needs one; publishing does not.", agentAction: "contact_support" },
  { code: "CONTENT_GROUNDING_FAILED", type: "validation_error", status: 422, retryable: false, message: "A generated claim could not be traced to the source it cites.", agentAction: "edit_ungrounded_claims" },
  { code: "SOURCE_NOT_FOUND", type: "not_found_error", status: 404, retryable: false, message: "No such content source." },
  { code: "DRAFT_SET_NOT_FOUND", type: "not_found_error", status: 404, retryable: false, message: "No such draft set." },
  { code: "INTERNAL_ERROR", type: "api_error", status: 500, retryable: true, message: "An unexpected error occurred.", agentAction: "retry_after_delay" },
  { code: "NOT_IMPLEMENTED", type: "api_error", status: 501, retryable: false, message: "This operation is not implemented yet." },
  { code: "FEATURE_DISABLED", type: "api_error", status: 403, retryable: false, message: "This feature is not enabled for your project.", agentAction: "contact_support" },
  { code: "SIMULATION_ONLY", type: "api_error", status: 403, retryable: false, message: "This operation is only available in simulation mode.", agentAction: "use_live_environment" },
];
